### ISSUE TITLE
Adjust the Getting Started guide

### ISSUE THREAD

**Issue by Orasund** [supermario/lamdera-realworld#4]
I've just cloned the project and tried to get the project running as described in the README. I needed to rerun a few of the commands before it actually worked. Here is what I did:

```
git clone git@github.com:supermario/lamdera-realworld.git
cd lamdera-realworld
lamdera reset
elm-spa make
lamdera reset
lamdera make src/Frontend.elm
elm-spa make
lamdera live
```

**Comment by supermario** [comment]
Hey @Orasund – thanks for pointing this out!

It seems the issue I didn't spot here was that `elm-spa make` isn't using the Lamdera compiler. Unfortunately it also doesn't seem to support the `ELM_COMPILER` env override.

In any case, this made me realise that `.elm-spa` source needs to be committed anyway for a Lamdera deploy to succeed.

Once that's the case and that source is already present on checkout, building the project should be a lot simpler and not require the `elm-spa make` part, thus avoiding the build cache conflicts, so I've updated the readme to that effect for now.

Let me know if that helps, or if you still have issues! 😊

**Comment by Orasund** [comment]
I've recloned and followed the constructions. Worked perfectly 👌
